### ISSUE TITLE
prep_silva_taxonomy problem

### ISSUE THREAD

**Issue by alk224** [mikerobeson/Misc_Code#1]
Getting strange problem with prep_silva_taxonomy script.  I run the prep_silva_data and everything appears fine:

head -1 trunc_rawtax.txt 
HE610125.2844.7343  Eukaryota;Viridiplantae;Chlorophyta;Trebouxiophyceae;Microthamniales;Stichococcus;Stichococcus bacillaris

head -2 trunc_seqs.fas 

> HE610125.2844.7343
> TTTTGACCTGAGATCAGACAAGACCACCCGCTGAACTTAAGCATATCAATAAGCGGAGGAA

Seqs are in sync with tax lines.

But after running prep_silva_taxonomy_file, the tax file is totally out of order:

head -1 trunc_tax.txt
AKZY01000201.42379.45235    D_0__Bacteria;D_1__Proteobacteria;D_2__Alphaproteobacteria;D_3__Rhizobiales;D_4__Rhizobiaceae;D_5__Ensifer;D_6__Sinorhizobium meliloti A0641M;D_7__;D_8__;D_9__;D_10__;D_11__;D_12__;D_13__;D_14__;D_15__;D_16__;D_17__;D_18__;D_19__;D_20__;D_21__

Everything is listed as domain level as well which doesn't bother me as much.

**Comment by alk224** [comment]
Actually, I don't think D is meant as domain here.  Whatever it means, it doesn't really matter, I just need to use SILVA LSU.

**Comment by alk224** [comment]
OK, things seem to be working now.  I had to run another script from Tony Walters to remove nonstandard characters this script missed (https://gist.github.com/walterst/0a4d36dbb20c54eeb952).

Closing

**Comment by mikerobeson** [comment]
Sorry for the delay. I am currently away on travel. Glad you figured it out! I was aware of the scripts inability to remove he non-standard characters. I just forgot to mention this. I'll update the script use text.
